version: '3.6'
services:
    app:
      build: .
      command: "npm start"
      ports:
        - "4200:4200"
        - "49153:49153"
      expose:
        # Port for ng serve
        - "4200"
        # Port for Webpack Hot Module Reload
        - "49153"
      # Maps the current directory to the Dockerfile's content
      volumes:
        - "./:/usr/app/"